### ISSUE TITLE
NO Offset Option

### ISSUE THREAD

**Issue by ghost** [cmpolis/scrollIt.js#1]
It would be nice if there was an offset option. In your demo, the nav's active state doesn't change until the panel meets the very top of the document / screen. It should transition when the panel meets the bottom of the nav. So in this case, the offset would be the height of the nav. Thoughts?

**Comment by knicklabs** [comment]
I have had the same issue. This leads to glitchy behaviour with keyboard navigation, where you cannot trigger a slide to the next region unless you ensure the current slide has cleared the top of the window. Tall fixed navbars make this issue much more noticeable. It's a great plugin, but I would love to see this fixed.

**Comment by cmpolis** [comment]
I agree - I'll put this in soon.

To remedy the problem, I just added top padding to each section equal to the height of the navigation.

**Comment by cmpolis** [comment]
Fixed in c8e5cd0ae7, c4e2697a73. The option is _topOffset_.
