### ISSUE TITLE
Question: on() method binded twice?

### ISSUE THREAD

**Issue by bbbiiiaaa** [cmpolis/scrollIt.js#11]
Hi,
Your plugin works great. I have one question, though. In this line you bind the watchActive handler to the scroll event and you use the `on()` method again. Could you explain me why?

``` javascript
$(window).on('scroll',watchActive).on('scroll')
```

**Comment by cmpolis** [comment]
Great question - it looks like someone _incorrectly_ refactored the binding from:

``` JavaScript
$(window).scroll(watchActive).scroll();
```
