### ISSUE TITLE
Clicking sub-elements inside of data-scroll-nav element does not work

### ISSUE THREAD

**Issue by ethicka** [cmpolis/scrollIt.js#15]
If you wrap text inside of the data-scroll-nav element and have padding on the `<a>` tag only clicking on the surrounding `<a>` area scrolls the page.

Clicking inside the element (e.g. inside the `<span>` below) does not scroll the page.

`<a href="javascript:;" data-scroll-nav="0"><span class="name">Travel</span></a>`

Here's a screenshot of the issue:

![example](https://f.cloud.github.com/assets/1000338/1507933/7b740136-49be-11e3-9a0c-be3c5a070b47.png)

This may be a unique use case, but it had me scratching my head for a bit why it wasn't working. Just in case someone else runs across this issue…

**Comment by ghost** [comment]
The Problem still exists.

I used the newest version with the supposed #15 fix, but when clicking on a span-element inside the a-area, the script won't work.

I hope you can fix this :)

If you are quick enough, you can check it out at http://qoolpack.com/wip/
