### ISSUE TITLE
Cannot handle more than 9 sections

### ISSUE THREAD

**Issue by seyDoggy** [cmpolis/scrollIt.js#3]
If your data-scroll-index is greater than 9, scrollIt will cease to scroll beyond the first section or two. I haven't been able to determine the cause of the issue myself. Still investigating.

**Comment by seyDoggy** [comment]
Issue still exists. If you try it in the demo site, make more then 9 sections, it fails after the 2nd or 3rd navigation.

**Comment by liamcrean** [comment]
Agreed. This still fails on more than 9 items. Will see if I can find a fix.
