### ISSUE TITLE
scrollIt not activating until scroll (1px off or something)

### ISSUE THREAD

**Issue by corysimmons** [cmpolis/scrollIt.js#7]
http://jeetframework.com/demo/scrollspy/

It might be a problem with my custom "fixed" nav [plugin](https://github.com/CorySimmons/relatively-sticky) but it seems to work fine when I just scroll regularly, but when I click a link, it gets the `.active` class seemingly randomly. If I scroll a nudge down then it seems to activate properly.

Any idea?

**Comment by corysimmons** [comment]
Here's the code: https://github.com/CorySimmons/jeetframework.com/tree/master/demo/scrollspy

**Comment by being-frank** [comment]
I am experiencing the same issue.

As a work around I modified [line 49](https://github.com/cmpolis/scrollIt.js/blob/master/scrollIt.js#L49) with the following code. `var targetTop = $('[data-scroll-index=' + ndx + ']').offset().top + settings.topOffset + 1;`

I will open a PR if this fixes the problem

**Comment by corysimmons** [comment]
Yeah I just tested this and it totally works. It lines up the pixels and everything. Kudos @fr4nktic 

Gonna go ahead and fork, let me know if you end up pulling this and I'll delete fork.

**Comment by corysimmons** [comment]
https://github.com/CorySimmons/scrollIt.js

**Comment by being-frank** [comment]
You can gladly create the PR :)

**Comment by corysimmons** [comment]
Hell, it's `+ 1` added to one line. Too lazy to press the button. ;)

**Comment by cmpolis** [comment]
Merged, thanks!
